CREATE TABLE COMPANY_Location(
        ID number CONSTRAINT CLocation_PK PRIMARY KEY,
        Location VARCHAR2(255) NOT NULL,
        Company int NOT NULL  CONSTRAINT Comp_FK_Loct REFERENCES Company(ID) ON DELETE CASCADE
);
