CREATE TABLE COMPANY_Phone(
        ID number CONSTRAINT CPhone_PK PRIMARY KEY,
        Phone NUMBER NOT NULL,
        Company int NOT NULL CONSTRAINT Comp_FK_Phone REFERENCES Company(ID) ON DELETE CASCADE
);
