CREATE TABLE COMPANY_SERVICE(
        ID number CONSTRAINT CService_PK PRIMARY KEY,
        Service VARCHAR2(55) NOT NULL,
        Company int NOT NULL CONSTRAINT Comp_FK_SERVICE REFERENCES Company(ID) ON DELETE CASCADE
);
