CREATE TABLE COMPANY_SERVICE(
        S_id number CONSTRAINT CService_PK PRIMARY KEY,
        CService VARCHAR2(55) NOT NULL,
        CompanyId int NOT NULL CONSTRAINT Comp_FK_SERVICE REFERENCES Company(C_Id) ON DELETE CASCADE
);
