CREATE TABLE LOOKINGFOR(
    App_ID number CONSTRAINT APPID_FK REFERENCES Applicant(ID) on DELETE CASCADE,
    Job_Id number CONSTRAINT JobID_FK REFERENCES Job(ID) on DELETE CASCADE,
    Major_Type VARCHAR2(25) NOT NULL,
    count NUMBER default 0,
    PRIMARY KEY (App_id,Job_id)
);
