CREATE TABLE Person(
    ID NUMBER CONSTRAINT USER_PK PRIMARY KEY,
    Phone_Number number,
    Email VARCHAR2(255) NOT NULL UNIQUE,
    registration DATE NOT NULL,
    Description VARCHAR2(255),
    F_Name VARCHAR2(15) NOT NULL,
    L_Name VARCHAR2(15) NOT NULL,
    Gender VARCHAR2(7) NOT NULL
);
